CREATE TABLE transactions (
    transaction_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    copy_ISBN VARCHAR(20), -- Giả sử ISBN là VARCHAR(13)
    borrowed_date DATE,
    return_date DATE,
    actual_return_date DATE,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (copy_ISBN) REFERENCES copies(copy_ISBN)
);



CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,  -- Tự động tăng giá trị id
    email VARCHAR(100) NOT NULL,
    username VARCHAR(100) ,     -- Tên người dùng
    age INT,                            -- Tuổi
    password VARCHAR(255) NOT NULL,     -- Mật khẩu
    phoneNumber VARCHAR(20),            -- Số điện thoại
    dob DATE,                           -- Ngày sinh
    role ENUM('admin', 'client') NOT NULL DEFAULT 'client',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Thời điểm tạo tài khoản
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- Thời điểm cập nhật cuối cùng
);


CREATE TABLE documents (
    documentId INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    year INT,
    genre VARCHAR(255) NOT NULL,
    ISBN VARCHAR(20),
    author VARCHAR(255),
    urlImage VARCHAR(255),
    number_of_copies INT,
    description TEXT
);



CREATE TABLE copies (
    document_id INT,
    copy_ISBN VARCHAR(20) UNIQUE,
    status ENUM('Available', 'Checked Out') DEFAULT 'Available',
    FOREIGN KEY (document_id) REFERENCES documents(documentId) ON DELETE CASCADE
);



CREATE TABLE client (
    user_id INT,                                 -- Khóa ngoại tham chiếu đến users
    borrowed_books INT DEFAULT 0,                -- Số sách mượn
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE   -- Khóa ngoại tham chiếu đến users
);

-- Bảng admin với admin_id là AUTO_INCREMENT
CREATE TABLE admin (
    user_id INT,                                 -- Khóa ngoại tham chiếu đến users
    -- Có thể thêm các thuộc tính riêng của admin tại đây
    FOREIGN KEY (user_id) REFERENCES users(id)  ON DELETE CASCADE  -- Khóa ngoại tham chiếu đến users
);
### This Trigger is used for whenever user is created, it auto create client with this user_id.

DELIMITER //

CREATE TRIGGER after_user_insert
AFTER INSERT ON users
FOR EACH ROW
BEGIN
    IF NEW.role != 'admin' THEN
            INSERT INTO client (user_id, borrowed_books)
            VALUES (NEW.id, 0); -- Khởi tạo borrowed_books với giá trị 0
    END IF;
END; //

DELIMITER ;

DELIMITER //

CREATE TRIGGER after_user_insert_admin
AFTER INSERT ON users
FOR EACH ROW
BEGIN
    -- Kiểm tra xem role của người dùng mới thêm vào có phải là 'admin' không
    IF NEW.role = 'admin' THEN
        INSERT INTO admin (user_id) VALUES (NEW.id);
    END IF;
END;

//

DELIMITER ;

### This Trigger is used for whenever Document is insert . it generate automatically 5 copies of document.
### ISBN has postprefix -1 -2 -3 -4 -5

DELIMITER //

CREATE TRIGGER after_document_insert
AFTER INSERT ON documents
FOR EACH ROW
BEGIN
    DECLARE i INT DEFAULT 1;
    DECLARE new_isbn VARCHAR(20);

    WHILE i <= NEW.number_of_copies DO
        -- Tạo một ISBN ngẫu nhiên (hoặc bạn có thể sử dụng một quy tắc tạo ISBN cụ thể)
        SET new_isbn = CONCAT(NEW.ISBN, '-', i);  -- Ví dụ: 'ISBN-1', 'ISBN-2', ...

        INSERT INTO copies (document_id, copy_ISBN)
        VALUES (NEW.documentId, new_isbn);

        SET i = i + 1;
    END WHILE;
END;

//

DELIMITER ;
